# include pywal colors
include ~/.config/kitty/colors-kitty.conf

# font_family JetBrainsMono Nerd Font
font_family Caskaydia Cove Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
cursor_trail 1
background_opacity 0.6

font_size 14.0
shell /usr/bin/fish

initial_window_width 95c
initial_window_height 35c

enable_image_protocol yes
enable_audio_bell no

# window
window_padding_width 5
window_margin_width 5
window_border_width 2px
active_border_color #abc2be
inactive_border_color #3D8185
enabled_layouts Tall, *
