# This blikizz Hyprland config file.
# Refer to the hyprland wiki for more information.
# https://wiki.hypr.land/Configuring/

source = ~/.config/hypr/dependencies/apps.conf
source = ~/.config/hypr/dependencies/monitor.conf
source = ~/.config/hypr/dependencies/auto-launch.conf
source = ~/.config/hypr/dependencies/variable.conf
source = ~/.config/hypr/dependencies/vibe.conf
source = ~/.config/hypr/dependencies/animations.conf
source = ~/.config/hypr/dependencies/input.conf
source = ~/.config/hypr/dependencies/keybind.conf
source = ~/.config/hypr/dependencies/window-rule.conf
source = ~/.config/hypr/dependencies/permission.conf
