#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
exec-once = waybar
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = wireplumber
exec-once=/usr/lib/polkit-kde-authentication-agent-1
exec-once=/usr/bin/dunst
exec-once = swww-daemon
